spring:
  redis:
    port: 6379
    host: 81.70.191.196
    database: 0
    password: SduKgSE_redis!
  messages:
    encoding: UTF-8
    baseName: i18n/messages
    fallbackToSystemLocale: false
  datasource:
    druid:
#      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:p6spy:mysql://120.46.182.143:3306/user125db?allowMultiQueries=true&characterEncoding=utf8&serverTimezone=Hongkong&useSSL=true&nullNamePatternMatchesAll=true&autoReconnect=true
      url: jdbc:mysql://81.70.191.196:3306?allowMultiQueries=true&characterEncoding=utf8&serverTimezone=Hongkong&useSSL=true&nullNamePatternMatchesAll=true&autoReconnect=true
      username: visitor
      password: SduEduSE2035!
      #初始连接池值
      initial-size: 10
      #最大连接数
      max-active: 100
      #最小连接数
      min-idle: 10
      #连接等待时间
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #配置StatViewServlet监控页面
      stat-view-servlet:
        #开启
        enabled: true
        #访问监控路径的地址
        url-pattern: /druid/*
        #不允许清空，重新统计
        reset-enable: false
        #登录用户名
        login-username: admin
        #登录密码
        login-password: admin
        #允许访问地址
        allow: 127.0.0.1
      ########## 配置WebStatFilter，用于采集web关联监控的数据 #########
      web-stat-filter:
        #启动statFilter
        enabled: true
        #排除的url
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        #开启session统计
        session-stat-enable: true
        #session的最大个数，默认为100
        session-stat-max-count: 1000
        #过滤的url
        url-pattern: /*
      filter:
        stat:
          #开启慢sql统计
          log-slow-sql: true
          #慢sql的时间
          slow-sql-millis: 2000
          merge-sql: true
          #开启druid datasource监控
          enabled: true
        wall:
          config:
          multi-statement-allow: true
mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  config-location: classpath:mybatis/mybatis-config.xml
      mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  port: 8082